import glob
import yaml
import os

def _create_index_rst():
    # Get the yaml configuration
    with open("config.yaml", "r") as f:
        config = yaml.safe_load(f)
    
    # Get all the files in the doc directory
    files = glob.glob(config['docpub']['path']+"/*.md")

    # Create the index.rst file
    with open(config['docpub']['path']+"/index.rst", "w") as f:
        f.write("doc-gen.ai Generated Documentation\n")
        f.write("==================================\n\n")
        f.write("Welcome to the sample documentation generated by doc-gen.ai. This documentation was created by running two (otherwise undocumented) code files through three Inference Providers which were prompted to generate documentation for the given source files.\n\n Below and in the sidebar you will find links to the original code files and the generated documentation. The generated documentation files are prefixed with the name of the Inference Provider used to generate the documentation. Currently three Inference Providers are supported: Google AI, Hugging Face and Open AI. The actual LLM used to generate the documentation is listed inside the documentation files itself after each major section.\n\n The purpose of this page is to provide a sample, essentially an overview of the ability for various LLMs to document otherwise undocumented code and the capability of doc-gen.ai as a driver for that documentation generation.\n")
        f.write("\n")
        f.write(".. toctree::\n")
        f.write("   :maxdepth: 2\n")
        f.write("\n")
        files.sort()
        for file in files:
            f_split = file.split("/")
            f_name = f_split[len(f_split)-1]
            if os.path.isfile(file):
                f.write("   "+ f_name +"\n")
        f.close()

_create_index_rst()